### ISSUE TITLE
Mayfly vs. K8s Jobs

### ISSUE THREAD

**Issue by alifiroozi80** [NCCloud/mayfly#15]
Hello everyone,
Saw this project today, and it is excellent!
But I came to a question:

It's very **similar** to the K8s Job concept.
I know how it's different from K8s Jobs, but I need to know the Mayfly use cases and **when** I should go with it instead of K8s Jobs.

**Comment by olivernadj** [comment]
The concept of K8s Job is to run one or more ephemeral Pods and it makes sure the tasks on those Pods terminate successfully. 

Meanwhile Mayfly operator is helping you to clean up any K8s object. It acts like you can specify `.spec.activeDeadlineSeconds` not only on Pods and Jobs, but literally any K8s object.


Eg.: I have a backup CronJob what makes a database dump in an ephemeral volume and uploads into external NAS. Once the job is finished the local dump is destroyed with the volume. Now I am using permanent volume with  `mayfly.cloud.namecheap.com/expire: 3600s` annotation, so I can quickly reuse the most recently dump locally if needed.

It can be also useful if you eg.: would like to provide someone with temporary resources, such us DB access, storage, config etc.

**Comment by alifiroozi80** [comment]
Thank you, @olivernadj, 
So, if I set the `mayfly.cloud.namecheap.com/expire: 3600s` on a, for example, a Job, after the successful execution of the Job, it won't remove until it reaches the `3600s`?

**Comment by olivernadj** [comment]
If you add `mayfly.cloud.namecheap.com/expire: 3600s` to a Job annotation, it will be removed by Mayfly operator after 3600s of its creation, regardless of failures or execution time.
In other words, Mayfly will not remove the Job until the the expiration time reached. Also Mayfly will not prevent CronJob to clean up Jobs history.
