### ISSUE TITLE
[proposal] Add a functionality to remove object on exact date \ time

### ISSUE THREAD

**Issue by eshepelyuk** [NCCloud/mayfly#20]
It would be great to have a possibilty to be able to schedule k8s resource removal not only after particular period but also via providing a desired date \ time.

Since `gocron` supports cron expressions, my suggestion is to add another annotation where one could provide cron expression for when resource should be deleted.

wdyt, is it possible ?

**Comment by sandromodarelli** [comment]
thank you @eshepelyuk for your suggestion. as you can see, our golang grand master @yunussandikci already open a PR. it was an already planned feature, so we decided to give some more priority with your request

**Comment by eshepelyuk** [comment]
> thank you @eshepelyuk for your suggestion. as you can see, our golang grand master @yunussandikci already open a PR. it was an already planned feature, so we decided to give some more priority with your request

Not sure I understand you. The single open PR is about scheduled object creation and it is also using period notation, not cron.

So how is that PR related to my proposal ?

**Comment by eshepelyuk** [comment]
Why the issue was closed ?

**Comment by yunussandikci** [comment]
@eshepelyuk Hello, I guess this issue has been linked with the wrong PR. Thanks for notifying 👍

**Comment by sandromodarelli** [comment]
Sorry, @eshepelyuk, my bad 🙏. I messed up the features. Could you please provide an example of the expected annotation format? It would be great to have a use case for the feature too

**Comment by eshepelyuk** [comment]
> Sorry, @eshepelyuk, my bad 🙏. I messed up the features. Could you please provide an example of the expected annotation format? It would be great to have a use case for the feature as well

* Use case - as i user I want a k8s resource to be deleted  at 21: 35 of 22 April of 2024
* annotations example
    ```yaml
    metadata:
         annotations:
                 ua.iesh/expire: "2024-04-22T22:35:00.0000000"
    ```

**Comment by eshepelyuk** [comment]
Hi @yunussandikci thanks for the fix

May I ask the clarification, is this new format working only for resource deletion ?
Or it also supported in scheduled resource creation ?

**Comment by eshepelyuk** [comment]
And could you plz add the desription of supported date formats to README, so the feature would have better visibility for users.

**Comment by yunussandikci** [comment]
@eshepelyuk New format is for both resource creation and expiration. I will update readme when I can, you can also create a PR since this is an open-source project. Thank you 👍
