### ISSUE TITLE
Allow grouping kinds of same groupVersion

### ISSUE THREAD

**Issue by RafaelBroseghini** [NCCloud/mayfly#81]
Instead of having to specify `groupVersion;Kind` repeatedly for same groupVersion, I'd like to be allowed to pass the first groupVersion and have it match all other adjacent kinds. 

For example, instead of:
```bash
RESOURCES=mylong.customresource.com/v1;CustomA,mylong.customresource.com/v1;CustomB,mylong.customresource.com/v1;CustomC
```
I'd like to use:

```bash
RESOURCES=mylong.customresource.com/v1;CustomA;CustomB;CustomC
```

**Comment by RafaelBroseghini** [comment]
Here's my PR: https://github.com/NCCloud/mayfly/pull/82

**Comment by yunussandikci** [comment]
Hello @RafaelBroseghini I believe that this will cause confusion while setting up the resources environment variable because there is while `,` seperates items `;` seperates both apiVersion and multiple kinds.
